### ISSUE TITLE
Deliver SqlQuery as a PHP extension

### ISSUE THREAD

**Issue by cyberhck** [auraphp/Aura.SqlQuery#103]
Hey, do you have any plans to deliver this project as a PHP extension so that PHP wouldn't need to parse these stuff on each stuff and would remain on memory and make it 10 times faster? Just curious :)

**Comment by pmjones** [comment]
If you are interested in writing it for PHP 7, I would be happy to review. :-)

**Comment by cyberhck** [comment]
You mean as a extension or just this project? @pmjones

**Comment by pmjones** [comment]
I mean Aura.SqlQuery as a PHP7 extension.

**Comment by cyberhck** [comment]
I'd love to, but I'm currently working on something which takes up all my free time. Maybe someone else want to take it up?

**Comment by pmjones** [comment]
It's a huge undertaking. For now, I'm closing this issue, but if someone wants to try for it I'm happy to re-open.
