### ISSUE TITLE
addRow missing on the interface

### ISSUE THREAD

**Issue by cdekok** [auraphp/Aura.SqlQuery#107]
addRow is missing on the InsertInterface so autocomplete wont work in my IDE, also it makes it easy to write code which is not compatible with the interface.

I think all public methods in the default insert class should also be in the insert interface.

**Comment by harikt** [comment]
Related : https://github.com/auraphp/Aura.SqlQuery/issues/92

**Comment by pmjones** [comment]
This appears to be fixed by various commits to the 3.x branch since the issue was entered. Please let us know if there are other problems!
