### ISSUE TITLE
binValuye doesn't return the current object

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.SqlQuery#11]
Hello,
in abstract query
 public function bindValue
return void.

In the given example we see that there is a chain pattern
$update
    ->table('foo')                  // update this table
    ->cols([                        // these cols as "SET bar = :bar"
        'bar',
        'baz',
    ])
    ->set('date', 'NOW()')          // set this col to a raw value
    ->where('zim = :zim')           // AND WHERE these conditions
    ->where('gir = ?', 'doom')      // bind this value to the condition
    ->orWhere('gir = :gir')         // OR WHERE these conditions
    ->**bindValue('bar', 'bar_val')**   // bind one value to a placeholder
    ->**bindValues([**                  // bind these values to the query
        'baz' => 99,
        'zim' => 'dib',
        'gir' => 'doom',
    ]);

But this stuff doesn't work....

fix : add a return $this;

**Comment by harikt** [comment]
Hey @Grummfy  could you open a PR with the patch .

Thanks

**Comment by harikt** [comment]
@Grummfy Have added .

Thank you for pointing to this.

**Comment by Grummfy** [comment]
sorry to forget to make a patch.. but thanks for fixing it.

**Comment by pmjones** [comment]
Good catch @Grummfy and thanks for fixing it @harikt

**Comment by harikt** [comment]
Thank you.
