### ISSUE TITLE
Drop 5.6 support for new versions

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.SqlQuery#118]
Hi all,

PHP 5.6 has EOL. How about newer versions concentrate on PHP 7.0 ? Reason is when we are releasing 7 may be already moved too far. So concentrating on 7 now may help.

Thoughts ?

/ cc @pavarnos .

**Comment by nyamsprod** [comment]
PHP5.6 is not technically EOL but yes dropping PHP5 support sound like a good move.

- http://php.net/supported-versions.php
- http://php.net/eol.php

**Comment by cdekok** [comment]
It's actually still supporting 5.3.9 i would prefer php 7, but it would be nice if the library could at least be bumped to 5.6 currently phpstan is complaining about the where method because it cannot use variadics as a feature and it has no support for the variadic docblock.

**Comment by pmjones** [comment]
The stated rule for Aura 3.x is that it should support 5.6, and test successfully on 7.

http://auraphp.com/blog/2015/03/27/aura-3-plans/

**Comment by harikt** [comment]
@pmjones you may want to consider revising the post for it was written in 2015 and now it is 2017 ;-) .

**Comment by pmjones** [comment]
Yea, and 5.6 is still the plan for 3.x.  4.x and later can target 7.0.
