### ISSUE TITLE
json data search

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.SqlQuery#122]
It looks mysql 5.7+ , pgsql etc now have json data types and have search functionalities.

May be good to introduce these new features.

https://dev.mysql.com/doc/refman/5.7/en/json.html#json-paths

https://www.postgresql.org/docs/9.3/static/functions-json.html

**Comment by pmjones** [comment]
What would be needed to support these, that the query system does not already have?

**Comment by harikt** [comment]
@pmjones good question. This is actually possible with the current way. I did tested it on a few stuffs, but I wonder if there is a way we can improve the signature. 

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use Aura\SqlQuery\QueryFactory;

$query_factory = new QueryFactory('mysql');

$select = $query_factory->newSelect();

$select->cols(['jdoc->"$.key1"'])
    ->from('t1')
    ->where('jdoc->"$.key1"');

echo $select;
```

will produce something like 

```
SELECT
    jdoc->"$.key1"
FROM
    `t1`
WHERE
    jdoc->"$.key1" = 'value1'
```

So probably the best question to ask is how can we make this much easier. I was actually reading this article :  https://murze.be/2016/04/making-eloquent-models-translatable/

This was the signature that looks nice. I am still playing with so not sure if there is any pitfalls / making the same.

```
NewsItem::where('name->en', 'Name in English')->get();
```

Thank you
Thank you

**Comment by pmjones** [comment]
> NewsItem::where('name->en', 'Name in English')->get();

What does that convert to, as far as SQL? `SELECT * WHERE name->en = 'Name in English'` , or something else?

**Comment by harikt** [comment]
I haven't looked at the internals, but this should be converted to something as 

```
SELECT * FROM `t1` WHERE name->"$.en" = 'Name in English'
```

**Comment by pmjones** [comment]
> SELECT * FROM `t1` WHERE name->"$.en" = 'Name in English'

Gotcha.

I admit I am not eager to modify the query strings more than we already are. I'd prefer to leave the condition-building to the end user, so they have the full power, explicitness, and specificity of the underlying SQL structures.
