### ISSUE TITLE
Scrutinizer and data types

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.SqlQuery#125]
So i've been fiddling with Scrutinizer a bit. Got an interesting message I don't know how to resolve.

<img width="796" alt="scrutinizer" src="https://cloud.githubusercontent.com/assets/589595/22316606/2baec0fc-e3d3-11e6-9309-488af984b1b7.png">

where $this->database is an instance of
```php
class Database {
    /**
     * @return QueryFactory
     */
    protected function getQueryFactory()
    {
        if (empty($this->queryFactory)) {
            $this->queryFactory = new QueryFactory($this->isSqlite() ? 'sqlite' : 'mysql');
        }
        return $this->queryFactory;
    }

    /**
     * @return UpdateInterface
     */
    public function update()
    {
        return $this->getQueryFactory()->newUpdate();
    }
```

Seems like Scrutinizer is looking through the `@return` type declaration of Auras `newUpdate()` to the `@return` type declaration of `newInstance('Update')`.

Is this a scrutiniser problem or something Aura can fix by changing type declarations?

**Comment by harikt** [comment]
Hey @pavarnos , 

You have already found the problem. 

https://github.com/auraphp/Aura.SqlQuery/blob/dd81b57aeb43628180a9c70a4df58d872024d7f2/src/QueryFactory.php#L191

The  `QueryFactory` is having `@return AbstractQuery` , but it can be an instance of `Insert`, `Update`, `Delete` or `Select` interfaces. So the return type declared is wrong. I guess if we fix the return type, it will work as expected.

**Comment by pavarnos** [comment]
OK. What should the return type be?

**Comment by harikt** [comment]
@pavarnos ~~I am not sure whether we can write something like this.~~

```php
@return Common\SelectInterface|Common\InsertInterface|Common\UpdateInterface|Common\DeleteInterface
```

~~There is multiple return type in this case, ie why.~~ . This will work, I have tested with phpdocumentator and apigen .

**Comment by harikt** [comment]
@pavarnos if you have time, do send a PR. Else I will look sending one.

Thank you.

**Comment by pmjones** [comment]
@harikt @pavarnos Any PRs as a result of this issue?

**Comment by pavarnos** [comment]
Sorry I have no time. As @harikt showed above I think it is a one line fix

**Comment by harikt** [comment]
PR : https://github.com/auraphp/Aura.SqlQuery/pull/135
