### ISSUE TITLE
Select should throw exception when cols are missing

### ISSUE THREAD

**Issue by jakeasmith** [auraphp/Aura.SqlQuery#13]
According to [the mysql documentation](https://dev.mysql.com/doc/refman/5.0/en/select.html) a select expression should always have at least one "select_expr" - or in Sql_Query terms, at least one column. 

Given that, what do you think of having [`Select::buildCols()`](https://github.com/auraphp/Aura.Sql_Query/blob/develop-2/src/Common/Select.php#L565) throw an exception rather than return an empty string when no cols are given. It would give you a very obvious error message instead of a generic "invalid query" message.

**Comment by harikt** [comment]
I have talked on it as keeping a `*` if empty in version 1. Looking back I feel your idea of exception sounds good.

Thanks

**Comment by ralouphie** [comment]
I agree that the exception makes a lot of sense. It also keeps things explicit.

**Comment by pmjones** [comment]
I'm not a fan of checking the correctness of SQL statements at the PHP level. I used to do so, and it ended up being "a camel's nose under the tent". After a while people want a check for everything. @jakeasmith do you get where I'm coming from? (Still open to considering it, I just want to point out some opposing experiences. ;-)

**Comment by jakeasmith** [comment]
Haha. I get what you're saying. The problem is that the SQL error isn't clear and I can't see the query - unless I think to print out the generated string.

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM foo
where a=b' at line 1`

The error message doesn't actually say a required component of the query is missing and the word "near" makes me assume it isn't including the entire query string. Things like this shouldn't take 10 minutes and 2 developers to debug, but in this case it did.

Another (possibly worse) idea is to throw an exception with the sql error and the full query string.

**Comment by harikt** [comment]
I don't like the idea of fully query string for that can make things worse. 
But like the idea of exception.
