### ISSUE TITLE
Common quoter is always used when using common query factory

### ISSUE THREAD

**Issue by djmattyg007** [auraphp/Aura.SqlQuery#138]
See here: https://github.com/auraphp/Aura.SqlQuery/blob/3.x/src/QueryFactory.php#L209

This results in the common quoter being used when generating MySQL queries, which results in the incorrect quote type being used. Removing the `$this->common` check resolves the issue.

I believe this came about as part of the refactoring for https://github.com/auraphp/Aura.SqlQuery/pull/132.

**Comment by pmjones** [comment]
Good catch. If you want to send a PR for credit, cool; otherwise I will attend to it. Thanks!
