### ISSUE TITLE
Insert multiple rows with a single query

### ISSUE THREAD

**Issue by jakeasmith** [auraphp/Aura.SqlQuery#16]
Is there a way to build a query that inserts multiple value sets? 

`INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9);`

If not, do you think it makes sense to add that functionality?

**Comment by harikt** [comment]
This is a nice functionality to add. Currently we don't have this support.

**Comment by harikt** [comment]
I also love to have multiquery execution. But we already discussed this in Aura.Sql https://github.com/auraphp/Aura.Sql/issues/22

**Comment by pmjones** [comment]
I can see where this would be useful, but I'm afraid I have other things that have to take priority.  However, if you want to create a new MultipleInsert (or InsertMany or InsertMulti) class that exhibits this behavior and send a PR for it, I'd be happy to review.

**Comment by arcturial** [comment]
I am working on a prototype for doing bulk inserts.

https://github.com/arcturial/Aura.SqlQuery/tree/feature-bulk-insert

Once the idea is solid I will do some cleanup before doing a PR. Have a look when you have a moment to see if this is what you had in mind.

The way you would use it is as follows:

``` php
$query->newBulkInsert()
           ->cols(array('col1', 'col2', 'col3'))
           ->bindValues(array(
                    array(
                            'col1' => 'row1a',
                            'col2' => 'row1b',
                            'col3' => 'row1c',
                    ),
                    array(
                            'col1' => 'row2a',
                            'col2' => 'row2b',
                            'col3' => 'row2c'
                    )
             ));
```

**Comment by harikt** [comment]
@arcturial it looks good to me. Appreciate your good work on it.

**Comment by arcturial** [comment]
I moved the code to a new branch and changed it so that it now uses the same interface as the Insert() queries. 

https://github.com/arcturial/Aura.SqlQuery/tree/feature-bulk-insert

The behaviour of some of the methods had to change slightly (like `cols()` not supporting associative arrays) since we are dealing with bulk data and not single values, but I don't think this should cause usability problems. I am not really sure why someone would want to use `cols()` with an associative array when doing bulk inserts anyway.

**Comment by arcturial** [comment]
I updated the README in that branch with more detailed usage instructions.

**Comment by harikt** [comment]
@arcturial send a PR so it will be easy to get reviewed.

Thanks!

**Comment by arcturial** [comment]
https://github.com/auraphp/Aura.SqlQuery/pull/56, request created

**Comment by pmjones** [comment]
This has been added as of https://github.com/auraphp/Aura.SqlQuery/commit/c9dc2af5445216d73da57f3f3e9e296cdac90064

Many thanks to @arcturial for providing the impetus behind it.
