### ISSUE TITLE
Please release 2.8

### ISSUE THREAD

**Issue by syrm** [auraphp/Aura.SqlQuery#163]
`git diff 2.7.1 2.x`
Can you release 2.8 because 2.x have inline array not released

**Comment by harikt** [comment]
@syrm sorry I missed it.

I was going through the comments on https://github.com/auraphp/Aura.SqlQuery/pull/127 again. If it works for you, I will do a release soon.

**Comment by harikt** [comment]
Sorry for being too late. I have released 2.8.0 .

Closing for the time being. Apologies once again.
