### ISSUE TITLE
Inline interfaces for WHERE, ORDER BY statements, etc.

### ISSUE THREAD

**Issue by unkind** [auraphp/Aura.SqlQuery#167]
```php
interface SelectInterface extends QueryInterface, WhereInterface, OrderByInterface, LimitOffsetInterface
```
I understand that at some semantical level, `WHERE` statement in `SELECT` query probably is the same concept as `WHERE` in `UPDATE` query. It makes sense for lexer, etc.

But I don't understand how exactly it helps in practice on interfaces level, but I always face with situation when developers make chaining and IDE shows warnings like `Method 'bindValues' not found in ...\WhereInterface`. I hope there was no intention to reduce duplication, because it is not about DRY: http://verraes.net/2014/08/dry-is-about-knowledge/

I suggest to inline all the interfaces. In addition, you'll be able to add `execute()` method which would be different for each type of query, e.g.

```php
interface DeleteQueryBuilder
{
    public function from(string $from): self;
    public function where(string $cond): self;
    public function orWhere(string $cond): self;
    public function bindValue(string $name, string $value): self;
    /**
     * @param array $values
     * @return int number of affected rows
     * @throws QueryFailed
     * @throws ConnectionFailed
     */
    public function execute(array $values = []): int;
}

interface SelectQueryBuilder
{
    public function forUpdate(): self;
    // ...
    public function limit(int $limit): self;
    public function bindValue(string $name, string $value): self;
    /**
     * @param array $values
     * @return SuccessResult
     * @throws QueryFailed
     * @throws ConnectionFailed
     */
    public function execute(array $values = []): SuccessResult;
}
```

**Comment by unkind** [comment]
Moreover, probably it makes sense to generate interfaces for different DB types, it would make possible to explicitly support features of each SQL-dialect without hurting whole concept. Otherwise abstraction starts to leak or just limits user.

**Comment by djmattyg007** [comment]
Seems a shame to have closed this issue without any discussion of potential solutions. It would have been nice to explore alternatives such as fluent builders.

**Comment by unkind** [comment]
@djmattyg007 feel free to open similar issue. I just try to close old issues when maintainer is obviously ignores me.
