### ISSUE TITLE
PHP 5.3?

### ISSUE THREAD

**Issue by landsem** [auraphp/Aura.SqlQuery#17]
This library requires PHP 5.3 or later, but it uses Traits, which wasn't implemented in PHP until PHP 5.4.

**Comment by pmjones** [comment]
I thought we removed all the traits. Can you point them out?

**Comment by landsem** [comment]
Mysql/update.php
Line 25 and 26.
8. Mai 2014 19:23 skrev "Paul M. Jones" notifications@github.com følgende:

**Comment by pmjones** [comment]
I think you may have an older version. The current develop-2 does not use traits AFAICT.

**Comment by pmjones** [comment]
cf. https://github.com/auraphp/Aura.SqlQuery/blob/develop-2/src/Mysql/Update.php

**Comment by landsem** [comment]
Sorry, my bad! Had the latest release.
