### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Bilge** [auraphp/Aura.SqlQuery#170]
No commits or issues at all in 2019. Just want to be clear before I consider using it.

**Comment by pmjones** [comment]
Not "dead" -- just "mature" and still used as widely as it ever was.

Having said that, you may wish to consider [Atlas.Query](https://github.com/atlasphp/Atlas.Query) as more recent alternative. That library, and the other related Atlas libraries, are descndants of the Aura SQQL libraries.

**Comment by Bilge** [comment]
I did come across Atlas.Query before I posted this issue, but it seemed like the Aura version was more attuned to what I wanted to do than that, despite being more recent. Specifically, I *do not* want a query builder than depends on an active connection. That is because I already have an (async) library I want to use to talk to the database; I *only* want the query builder portion, so it needs to act independently of any database connection.

**Comment by pmjones** [comment]
> I only want the query builder portion, so it needs to act independently of any database connection.

Noted -- Aura.SqlQuery is going to be more your speed ...

... at least, for the time being. If you have the time and inclination, contact me by email, and maybe we can work out a way to modify Atlas.Query to support your use case. I have some ideas about that already but I want to make sure they're suitable for what you need.

**Comment by Bilge** [comment]
I have no problem using email, but why shouldn't we continue publicly? 

If you feel inclined to support my use-case in Atlas rather than in this library, that appears to already support it, isn't that further cementing the idea that you no longer want to maintain this project?

**Comment by pmjones** [comment]
> why shouldn't we continue publicly?

(/me shrugs) No difference to me, sometimes email is easier.

In any case, if you like this project, feel free to use and/or contribute to it. If you like the other, feel free to use and/or contribute to that one instead.
