### ISSUE TITLE
Is this a coding bug?

### ISSUE THREAD

**Issue by smallslime** [auraphp/Aura.SqlQuery#178]
https://github.com/auraphp/Aura.SqlQuery/blob/513747a1b399b910f6050e78bd64c3c125a81abf/src/Common/SelectBuilder.php#L59

        foreach (**$from** as $from_key => **$from**) {
            if (isset($join[$from_key])) {
                $from = array_merge($from, $join[$from_key]);
            }
            $refs[] = implode(PHP_EOL, $from);
        }

**Comment by djmattyg007** [comment]
It definitely doesn't look like a good idea.

**Comment by pmjones** [comment]
Gosh it sure looks like it. I will look into it more closely!
