### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by rotexdegba** [auraphp/Aura.SqlQuery#185]
What is the future of this project? In my opinion, it is feature complete and only needs to have the latest versions of PHP (7.3, 7.4 & 8.0 as of this writing) tested via travis or Github Actions to ensure it continues to work with the currently supported version of PHP. Will anyone be updating the CI tests for this project?

**Comment by AllenJB** [comment]
I'd specifically like to know what, if any, blockers / issues are currently known that are holding up a stable release of the 3.x branch?

Not having static analysis complain every time I use ->where() with 2 or more parameters (among other methods) is a very desirable feature.

(Related: I submitted a PR #186 which includes testing against PHP 8.0 which passes without issues)

**Comment by harikt** [comment]
Ci is updated via https://github.com/auraphp/Aura.SqlQuery/pull/195 . Now supports upto 8.1 .
