### ISSUE TITLE
Github actions updated

### ISSUE THREAD

**Issue by rotexdegba** [auraphp/Aura.SqlQuery#211]
Sent a pull request https://github.com/auraphp/Aura.SqlQuery/pull/210 which adds PHP 8.3  to the test suite & also fixes a Dynamic Property Deprecation warning for PHP 8.1+. 

Please kindly merge

**Comment by harikt** [comment]
Just a note : You don't need to create an issue. In case we miss, you can ping me.

Thank you.

**Comment by rotexdegba** [comment]
No problem. How do I ping you though? The only contact info for Aura packages I have seen is the google group which seems to be read-only, I couldn't post anything there

**Comment by harikt** [comment]
Have you joined the group https://groups.google.com/g/auraphp ? If so you can email I guess.

Regarding ping : what I mean is add @harikt in github notes like this.

**Comment by rotexdegba** [comment]
Yes I have joined the group. Ok, I will go with mentioning you in Github notes
