### ISSUE TITLE
AS should only be recognized as an alias if its the second to the last word

### ISSUE THREAD

**Issue by mbrevda** [auraphp/Aura.SqlQuery#22]
Currently, AS is parsed regardless of where it in the column string. It would seem that AS is only valid if its the second to the last word. i.e. `SELECT foo AS some alias here FROM...` is invalid syntax. This affect how quoting is done (in this case, the query will be quoted as  `SELECT `foo` AS `some alias here` FROM...`) which would produce an invalid query.

I think it would be more correct to only recognize AS if its the second to the last word in a string?

**Comment by pmjones** [comment]
Maybe, maybe not. Are you running into problems with the parsing as it is now, or is this a hypothetical? if a hypothetical, I think it's OK as-is, at least for now.

**Comment by mbrevda** [comment]
hypothetical
