### ISSUE TITLE
Autoquoting table names

### ISSUE THREAD

**Issue by Garfunk** [auraphp/Aura.SqlQuery#24]
Hi,

actually tables names are auto quoted. For example, calling 

```
->from('production.some_table')
```

will result in

```
FROM "production"."some_table"
```

in the final query.

Unfortunately, sometimes (with postgreSQL at least) we may need to call a function. And function name must NOT be quoted, or it triggers an error.

```
->from('production.some_function()')
```

will result in

```
FROM "production"."some_function()"
```

but it should be

```
FROM "production".some_function()
```

I can humbly propose 2 solutions:
- autodetect a function call (by detecting the brackets at the end of the table name), but i might be not really reliable,
- adding another method/an additional parameter to stop autoquoting the table name in the `from` method.

Thanks a lot !

**Comment by pmjones** [comment]
@Garfunk after trying the first suggestion, I disliked it, so I have ended up at your second suggestion. The new `Select::fromRaw()` method leaves the name unquoted. Try it out, let me know how it works for you.

**Comment by Garfunk** [comment]
OK thanks a lot :)
I'll try it as soon as I can update Composer safely.

**Comment by Garfunk** [comment]
I finaly got to update and I can tell you that it works like a charm, no more ugly str_replace :)
Thanks a lot !

**Comment by harikt** [comment]
@Garfunk great! . Good to hear.
