### ISSUE TITLE
Array support in conditions

### ISSUE THREAD

**Issue by thejw23** [auraphp/Aura.SqlQuery#29]
I guess for all those:

```
->where('bar > :bar')
```

it would be better to add support for arrays:

```
->where(array($field,$condition,$value))
```

it would make easier to build dynamic queries based on various conditions than current version with strings.

**Comment by harikt** [comment]
Don't know whether it is really worth.

**Comment by pmjones** [comment]
I agree with @harikt on this one. I don't see that it's "easier"; in fact, for things like "foo IN (:list)" or "bar BETWEEN :low AND :high" it is rather difficult.
