### ISSUE TITLE
Add a public method to generate SQL query

### ISSUE THREAD

**Issue by gauthier** [auraphp/Aura.SqlQuery#30]
Hi,

I'm using Aura.SqlQuery for a while - it's a really great package, making the job quite well. But I'm having some issues with more complicated queries, mostly implying subqueries: 

since the only way to get the query actually built, as a string, is magic method __toString, we cannot get informations about exceptions likely to be thrown when generating the query.

PHP forbid __toString method to throw Exceptions, so in such a case, the execution ends up with a Fatal Error, and no data about the thrown exception.

Could you please add something like `public function generateQuery()` so that we can debug when something goes wrong?

**Comment by harikt** [comment]
@gauthier Thank you.

In the mean time if you are using something like Aura.Sql does the profiler trace works for you ? https://github.com/auraphp/Aura.Sql#profiler

**Comment by gauthier** [comment]
Hi @harikt,

being new to Aura (I'm using it together with POMM - a third-party DAO layer for PostGreSQL), I didn't now other packages than Query Builder. I'll check if it can work it out.

Anyway, I think this could be helpful to dump the query without being encapuslated in the __toString() method.

The code in __toString() should be moved to a public method, and then __toString() would just contain `return $this->generateSql();`for instance

**Comment by gauthier** [comment]
after a very quick outlook on Profiler documentation, I don't think it could be of any help: PHP triggers a fatal error when the Exception is thrown, so the profiler won't be able to trace anything.

**Comment by pmjones** [comment]
> The code in __toString() should be moved to a public method, and then __toString() would just contain return $this->generateSql();for instance

If __toString() calls generateSql(), and generateSql() throws an exception, then that's equivalent to __toString() throwing an exception -- no? (I have not tested it.)

**Comment by gauthier** [comment]
@pmjones you're definitely right ; but implementing a method such as generateSql would allow to call it directly when needed, not passing through __toString

**Comment by chrisguitarguy** [comment]
:+1: on this. I like the use of `__toString` a lot -- it's super clean. But having something in `QueryInterface` to do the equivalent would be great. `toSql` or `build` (if you want to keep with the whole builder thing)?

``` php

$factory = new \Aura\SqlQuery\QueryFactory('mysql');
$select = $factory->newSelect();

// ...

$query = $select->toSql();
// or
$query = $select->build();
```

Much prettier than:

``` php
$query = $select->__toString();
```

I didn't really see the point of this until a few fatal errors from casting a query builder to a string popped up in my logs today.

**Comment by pmjones** [comment]
Can't change the interface, as that's a BC break, but I can add a `getStatement()` method.
