### ISSUE TITLE
make method cols() optional

### ISSUE THREAD

**Issue by antgubarev** [auraphp/Aura.SqlQuery#32]
by default the value array('*')

**Comment by harikt** [comment]
I don't think this will happen. 

We have discussed about it earlier https://github.com/auraphp/Aura.Sql/issues/10 

And working for sometime I feel we should not use  `SELECT *` in an sql query.

**Comment by pmjones** [comment]
@harikt is correct here. After having used a default '*' in a previous project, it is not something I'd like to see re-introduced. Sorry @apgubarev .
