### ISSUE TITLE
like not work

### ISSUE THREAD

**Issue by antgubarev** [auraphp/Aura.SqlQuery#35]
$select->where('field_name like ?',$field_var);
result
"WHERE field_name like ?" and mysql error

$select->where('field_name like :value');
$select->bindValue(array('value'=>$value));
result
"WHERE field_name like :value" and mysql error

**Comment by harikt** [comment]
@apgubarev try `$data[$column] = '%$value%'` as suggested at https://github.com/auraphp/Aura.Sql/issues/14#issuecomment-5480009 .

If that fixes please close the issue.
