### ISSUE TITLE
Hstore support for postgres

### ISSUE THREAD

**Issue by agentile** [auraphp/Aura.SqlQuery#36]
Any chance of doing some hstore to PHP array back and forth support? Similar to what is trying to be achieved here https://github.com/chanmix51/Pomm/blob/15cb95a4c0f1f91e4d5454de9614570ed5387e33/Pomm/Converter/PgHStore.php

**Comment by pmjones** [comment]
That's an interesting idea. My first thought is that we don't want the query system in charge of translating typed data into and out of the database. My second thought is that having a second package to do exactly that might be a good idea.

Over to you.

**Comment by agentile** [comment]
Sounds good to me. Seems like there are a few special data types out there that could benefit, hstore and json are the first to come to mind. I am betting they won't be the last. So your saying something more along the lines of having an Aura.SqlDataType (or otherwise appropriately named) to handle this conversion of data through PDO, which can then be tacked into Aura.Sql in some manner?

**Comment by pmjones** [comment]
yes, that sounds like a starter

**Comment by harikt** [comment]
and it does eval https://github.com/chanmix51/Pomm/blob/15cb95a4c0f1f91e4d5454de9614570ed5387e33/Pomm/Converter/PgHStore.php#L26 . Will it hurt ?

**Comment by pmjones** [comment]
eval() is evil ;-)

**Comment by pmjones** [comment]
The more I think about this, the more it looks a lot like a filter to be applied to data as it comes out of the DB, and as it goes back in. That makes it more suitable for Aura.Filter or something like that, probably applied at a Mapper layer. Same thing goes for JSON/JSONB as stored in Postgres 9.4.

With that in mind, I'm closing this as an SQL-specific issue.
