### ISSUE TITLE
Tag New Stable Release?

### ISSUE THREAD

**Issue by chrisguitarguy** [auraphp/Aura.SqlQuery#37]
The behavior of `SelectInterface::cols` is broken in 2.0.0: it's possible to duplicate columns in SQL and cause all sorts of fun errors.

This fixes [are already in `develop-2`](https://github.com/auraphp/Aura.SqlQuery/compare/auraphp:f5edf56...auraphp:c1c670f#diff-57cf575fdd7a21c19685563c9fa2a1c0R234).

**Comment by harikt** [comment]
@pmjones have some thoughts on pushing new releases this week. If he is able to he will push.

Thank you.

**Comment by pmjones** [comment]
Release imminent. Closing beforehand.
