### ISSUE TITLE
Should Queries Keep Track of Joined Tables?

### ISSUE THREAD

**Issue by chrisguitarguy** [auraphp/Aura.SqlQuery#38]
I'm building an application that uses a lot of other objects to modify an Aura query builder object.

One issue I ran into is that the query builders don't keep track of joined tables. So something like this:

``` php
use Aura\SqlQuery\QueryFactory;

$factory = new QueryFactory('mysql');

$select = $factory->newSelect();

$select->cols([
    'SUM(clicks)' => 'clicks',
]);
$select->from('some_table');
$select->join('other', 'some_table.id = other.id');

// some other object does it again
$select->join('other', 'some_table.id = other.id');

echo $select, PHP_EOL;
```

I would expect the join to only be generated a single time, but that's not the case:

``` sql
SELECT
    SUM(clicks) AS `clicks`
FROM
    `some_table`
OTHER JOIN `some_table`.`id` `=` `other.id`
OTHER JOIN `some_table`.`id` `=` `other.id`
```

It's easy enough to solve with client code, but it seems like it might be a nice feature for the query builders in general.

**Comment by staabm** [comment]
Sometimes you actually want to join tables twice (several times), so you need to verify first when aura could be smart enough..

**Comment by staabm** [comment]
Maybe aura could bring some methods so you can decide from within your app what joins are already present

**Comment by chrisguitarguy** [comment]
> Sometimes you actually want to join tables twice (several times), so you need to verify first when aura could be smart enough.

Correct. Doing that means using a separate alias, which means aura could keep track of it based on aliases.

> Maybe aura could bring some methods so you can decide from within your app what joins are already present

Maybe? Generally you tell objects to do things, not ask if you can. I'd rather see the the query builders themselves keep track of joins somehow and not have my client code know about it.

**Comment by pmjones** [comment]
This one's tough for me. @chrisguitarguy I see where you're coming from, it would be nice to have the object avoid duplicates. But as it stands now, the object doesn't do that for anything: not FROM, JOIN, WHERE, HAVING, ORDER BY, or anything else. Adding it for one of them would seem to require adding it for all of them for consistency and completeness. I'm reluctant to do that.

@chrisguitarguy further thoughts?

**Comment by chrisguitarguy** [comment]
> Adding it for one of them would seem to require adding it for all of them for consistency and completeness.

I disagree about that. `WHERE`, `HAVING`, `GROUP BY`, and `ORDER BY` are all okay to have multiple values. Having the same values in multiple positions of each of those isn't exactly great, but it's not harmful either. Harmful meaning that it doesn't produce errors. Here's a ridiculous example for a WordPress database:

``` sql
select 1
from wp_posts
WHERE post_type = 'post' AND post_type = 'post'
group by post_type, post_type
order by post_type ASC, post_type DESC;
```

Moreover, none of those clauses have unique identifiers. Tables and columns do: their aliases or names. SqlQuery keeps track of columns and makes sure there are no duplicates there. There's no reason tables, whose alias is the unique identifier, shouldn't be kept track of as well.

**Comment by pmjones** [comment]
> WHERE, HAVING, GROUP BY, and ORDER BY are all okay to have multiple values. Having the same values in multiple positions of each of those isn't exactly great, but it's not harmful either. 

OK, I can get behind that.

My first intuition is to build up the individual JOIN clause in its entirety, and then compare to existing JOIN clauses in their entirety, That would cover aliasing, joining on different conditions, etc. On a duplicate, do we silently discard, or do we throw an exception?

**Comment by chrisguitarguy** [comment]
> My first intuition is to build up the individual JOIN clause in its entirety, and then compare to existing JOIN clauses in their entirety

Risky, I think.

```
$q = $factory->newSelect();
$q->cols(['a.some_col', 'b.other_col']);
$q->from('table_one AS a')
$q->join('LEFT', 'table_two AS b', 'a.id = b.id');

// this would be let through because the condition is different but the alias is the same
// and it would produce an error from the database server
$q->join('LEFT', 'table_two AS b', 'a.some_col = b.some_col');
```

Even if comparison is done on full joins, I think aliases should be tracked so no duplicates are allowed. Trying to use a duplicate alias would an exception worthy event.

> On a duplicate, do we silently discard, or do we throw an exception?

I think there's precedent for this with columns: overwrite the existing value?

**Comment by pmjones** [comment]
I'm trying to elicit what would be a satisfactory set of conditions. Perhaps submitting a PR would be best at this point.

**Comment by pmjones** [comment]
Hm, on re-reading, it seems like you're saying the only thing to track is alias names. Is that correct?

**Comment by pmjones** [comment]
Or rather, the combined "table AS alias" string.

**Comment by chrisguitarguy** [comment]
Only track the alias name, was what I was saying.

**Comment by pmjones** [comment]
/me nods

I get you. Sorry to be dense. Essentially, for FROM and JOIN, keep the AS name, or the original name if there's no AS, to disallow duplicates.

Further, "Trying to use a duplicate alias would an exception worthy event." I'm OK with this, as we blow up when there a JOIN with no prior FROM.

I'll work something up, unless you do in the meantime.

**Comment by chrisguitarguy** [comment]
Sounds good. It's been a while since I've thought about this stuff, so I'm getting back up to speed myself (and realizing how bad my examples in the original issue are).

[We've](https://github.com/KoddiDev) had a reporting engine powered by SqlQuery running in production for about six months now without any issues.

**Comment by pmjones** [comment]
> powered by SqlQuery running in production for about six months now 

Dude. Sweet.

**Comment by pmjones** [comment]
Looking at it now, this may be a little flaky in some cases. E.g., in Postgres, `$select->from('table_name')` and later `$select->leftJoin('default_schema.table_name')` refer to the same table in the default schema, and ought to blow up, but we can't really tell from the outside that they're the same. My guess is that there are other similar cases. I don't like that, but I don't know how big a deal it is.

**Comment by pmjones** [comment]
@chrisguitarguy here's a starting point: https://github.com/auraphp/Aura.SqlQuery/commit/9f907be99b7d703cf05e314e58be7221c6e548bf

**Comment by pmjones** [comment]
@chrisguitarguy please review #51 and see if it suits your needs
