### ISSUE TITLE
Limit, offset and paging

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.SqlQuery#40]
Hi,
I find bad that if we directly set offset and limit to a select query, that getPaging() doesn't give an updated value.

By the way, I think it could be really intresting to have a getLimit() and a getOffset() method on Select . Why ? Because it's easier to extends, easier to test, ...

**Comment by harikt** [comment]
I believe you should make use of 

``` php
<?php
$query->setPaging(10);
$query->page(2);
```

which should set the offset and limit for you.

**Comment by harikt** [comment]
Here is what the code does https://github.com/auraphp/Aura.SqlQuery/blob/2.0.0/src/Common/Select.php#L474-L489 . Even if you don't set the `setPaging` by default it takes 10.

**Comment by Grummfy** [comment]
Yes, but without using setPaging, you can't have a getPaging relevant. So for me it's a bit confusing.

**Comment by harikt** [comment]
@Grummfy https://github.com/auraphp/Aura.SqlQuery/blob/2.0.0/src/Common/Select.php#L104 :-)

**Comment by Grummfy** [comment]
OKi, I just understand my confusion. getPaging() is the number of row per page (it's writen in the comment ...) and mixed it with a getPage() or whatever ... and my code. Well ok, my bad.

But for me, it should have two more accessors :
- getLimit()
- getOffset()

**Comment by harikt** [comment]
If you feel so, you should consider sending a PR and wait for Paul's thoughts or pressure him to merge ;) .
