### ISSUE TITLE
tables prefix

### ISSUE THREAD

**Issue by SebSept** [auraphp/Aura.SqlQuery#46]
Hi,

First I'd like to thank all contributors to share this :)

It looks like there is no support for table prefix.

``` php
$query_factory = new QueryFactory('sqlite', null, 'ps_');
```

So that each table name is prefixed with 'ps_' (from and joins)
I think it could be great.
- Is there a plan to provide it ?
- can it be done ? without introducing a breaking change ?

**Comment by pmjones** [comment]
Hi @SebSept :

> Is there a plan to provide it ?

Not in the core package, no.

> can it be done ? without introducing a breaking change ?

It probably can be done, but I don't find it suitable for this package. I've tried that sort of thing before and while it seems great at the start it ends up being more trouble than it's worth.

I suggest defining constants for your table names, or use a TableNames object of your own devising that tracks table names for you. That will allow you mix-and-match prefixes among different table sets, one prefixed with "wp_" for WordPress, another set prefixed with "ps_" for whatever PS is, and so on.

**Comment by SebSept** [comment]
> It probably can be done, but I don't find it suitable for this package. I've tried that sort of thing before and while it seems great at the start it ends up being more trouble than it's worth.

ok. Thanks for sharing experience. Maybe I'll implement it later, for the moment I did not need this package.

cheers .
