### ISSUE TITLE
Subselect generated by newSelect wrong quote

### ISSUE THREAD

**Issue by ag-secret** [auraphp/Aura.SqlQuery#47]
// Generating the select that later will be used as a subselect
$subSelect = $subQuery
  ->cols(['*'])
  ->from('table1 AS t1');

echo $subSelect->__toString();
// Below the result with all quotes correct
// SELECT \* FROM `table1` AS `t1`;

// Here the main select using the subselect generated above
$select = $query
  ->cols(['*'])
  ->from('table2 AS t2')
  ->where('field IN ('.$subSelect->__toString().')');

// Below the result with an unwanted extra quote
// SELECT \* FROM `table2` AS `t2` WHERE field IN (SELECT \* FROM `table1` AS **``t1`**); <- HERE

**Comment by ag-secret** [comment]
I got what is generating the issue. I'm giving the alias usin 'AS', eg. "table1 AS t1" but if I do it without "AS" eg. "table1 T1" is working.
I think this could mess with a lot of people.

**Comment by pmjones** [comment]
I'm trying to duplicate the problem in develop-2 and do not see it. I added this test to `tests/unit/src/Common/SelectTest.php`:

``` php
<?php
    public function testIssue47()
    {
        /* sub select */
        $sub = $this->newQuery()
            ->cols(array('*'))
            ->from('table1 AS t1');

        echo PHP_EOL . $sub . PHP_EOL;
        // SELECT
        //     *
        // FROM
        //     "table1" AS "t1"


        /* main select */
        $select = $this->newQuery()
            ->cols(array('*'))
            ->from('table2 AS t2')
            ->where("field IN (" . PHP_EOL . $sub . PHP_EOL . ")");

        // SELECT
        //     *
        // FROM
        //     "table2" AS "t2"
        // WHERE
        //     field IN (
        // SELECT
        //     *
        // FROM
        //     "table1" AS "t1"
        // )
        echo PHP_EOL . $select . PHP_EOL;
    }
?>
```

As you can see from the comments indicating output, the identifier quoting appears to be correct.

Can you provide further guidance, or a pull request with a failing test?

**Comment by pmjones** [comment]
Oho! I just ran the entire suite with that in place, and it _does_ show up, but only for MySQL and SqlServer. I'll take a closer look.

**Comment by pmjones** [comment]
The problem is that `Select::where()` ends up calling `AbstractQuery::addClauseCondWithBind()`, which in turn applies `Quoter::quoteNamesIn()` to the entire WHERE condition. Since the condition includes the entries sub-select string, the quoter is trying to find names there. Thus the weirdness around using `AS`.

**Comment by pmjones** [comment]
I would expect the same problem to show up in `orWhere()`, `having()`, and `orHaving()` as well.

**Comment by pmjones** [comment]
@ag-secret OK, take a look at https://github.com/auraphp/Aura.SqlQuery/commit/bc4a1fb2a2d25a78d0b64432dddab5ac1f7d583c in the issue-47 branch. This allows you to pass a Select object (any AbstractQuery, really) as a bound value, and the Select will convert it to a string and place it inline in the condition. This gets around the issue of quoting the entire condition.

Would that help?

**Comment by ag-secret** [comment]
Awesome, thanks.. It will be in the next release?

**Comment by pmjones** [comment]
> Awesome, thanks.

Good, I'll merge it soon.

> It will be in the next release?

Yes, although I have a few other merges that should go into it as well. Waiting for feedback on those.
