### ISSUE TITLE
complex sql query with parentheses

### ISSUE THREAD

**Issue by Slavka63** [auraphp/Aura.SqlQuery#48]
Hello , I need generate sql query

SELECT RAYON.NAME
    ,Count(DOGOVOR.NDOG) AS Count_NDOG
    ,Sum(DAY.DA) AS Sum_DA
FROM (
    (
        RAYON INNER JOIN OSNADRES ON RAYON.KRN = OSNADRES.KRN
        ) INNER JOIN (
        DOGOVOR LEFT JOIN DAY ON DOGOVOR.NDOG = DAY.NDOG
        ) ON OSNADRES.ARXNOM = DOGOVOR.ARXNOM
    )
INNER JOIN DOLGIPODOG ON DOGOVOR.NDOG = DOLGIPODOG.NDOG
GROUP BY RAYON.NAME
ORDER BY RAYON.NAME;

you can not remove the brackets

i got 
$select1->cols(array(
            'RAYON.NAME', 
             'Count(DOGOVOR.NDOG) AS Count_NDOG',
             'Sum(DAY.DA) AS Sum_DA'
    ))
       ->from('RAYON ')
        ->join( 'INNER','OSNADRES ','RAYON.KRN = OSNADRES.KRN')
        ->join ('INNER','DOGOVOR','DOGOVOR.NDOG = DAY .NDOG')
        ->join ('INNER','DOLGIPODOG','DOGOVOR.NDOG = DOLGIPODOG.NDOG')
        ->groupBy(array('RAYON. NAME'))
        ->orderBy(array('RAYON. NAME'));

what is wrong

please help correct

**Comment by pmjones** [comment]
Reformatted, but still with the parentheses:

``` sql
SELECT
    RAYON.NAME,
    Count(DOGOVOR.NDOG) AS Count_NDOG,
    Sum(DAY.DA) AS Sum_DA
FROM (
    (
        RAYON
            INNER JOIN OSNADRES ON RAYON.KRN = OSNADRES.KRN
    ) INNER JOIN (
        DOGOVOR LEFT JOIN DAY ON DOGOVOR.NDOG = DAY.NDOG
    ) ON OSNADRES.ARXNOM = DOGOVOR.ARXNOM
) INNER JOIN DOLGIPODOG ON DOGOVOR.NDOG = DOLGIPODOG.NDOG
GROUP BY RAYON.NAME
ORDER BY RAYON.NAME;
```

I have never seen anything like that before. I'm afraid you will have trouble building exactly that query with Aura.SqlQuery.

**Comment by pmjones** [comment]
Specifically, it looks like the problem is with the parentheses in the FROM/JOIN statements. I've not seen that kind of sub-FROM sub-JOIN before and can't imagine how to make it work in SqlQuery.
