### ISSUE TITLE
page() depends on setPaging() call order

### ISSUE THREAD

**Issue by ksimka** [auraphp/Aura.SqlQuery#49]
`page` method calcs limit and offset immediately, using current `paging` value

``` php
public function page($page)
    {
        // reset the count and offset
        $this->limit  = 0;
        $this->offset = 0;

        // determine the count and offset from the page number
        $page = (int) $page;
        if ($page > 0) {
            $this->limit  = $this->paging;
            $this->offset = $this->paging * ($page - 1);
        }

        // done
        return $this;
    }
```

In my opinion, one of the advantages of query builder is that method calls don't depend on their order. And in this case that rule is broken. You must call `setPaging` before `page`, otherwise `limit` and `offset` will be calced based on the default value.

So I think you should just save `page` and `paging` and calc its values only when building is invoked.

**Comment by pmjones** [comment]
You're right, it should not be order-dependent. I will review any PR you come up with; meanwhile I may try to fix it myself.

**Comment by ksimka** [comment]
I've tried to implement a quick fix, but looks like it needs a bit more time to fix it properly. Give me a couple of days.
