### ISSUE TITLE
Automatic table name prefix

### ISSUE THREAD

**Issue by skyosev** [auraphp/Aura.SqlQuery#55]
Hi,

It's a common practice to have table prefix per project installation, where multiple projects can reside in a single database. Currently I have to build my queries like:

`$select->from(DB_PREFIX . 'table1')`

I would like to have an optional global prefix per QueryFactory to be automatically prepended in all statements that involve table names. Is there an easy way to implement this ?

**Comment by pmjones** [comment]
Please see #46 regarding this. Short version: auto-adding prefixes seems great for the 80% cases, until you run into the the 20% cases, and then it seems horrible. I have supported that behavior in other, previous work; it's tougher to "do it right" than you think.

**Comment by skyosev** [comment]
Thanks for the reply. Should have browsed the issues before posting this. 

I suggest to add a note in the docs that Aura.SqlQuery does not and won't support table name prefixes out of the box in order to prevent similar questions.

**Comment by pmjones** [comment]
> add a note in the docs that Aura.SqlQuery does not and won't support table name prefixes out of the box

Good call. If you want to send a PR for that I can apply it, otherwise I'll so myself as time permits. Thanks!
