### ISSUE TITLE
Update composer package

### ISSUE THREAD

**Issue by kornrunner** [auraphp/Aura.SqlQuery#58]
Hi,

Could you please update composer package on packagist.org? It seems it is not providing new versions since v2.2.0. 

Thanks!

**Comment by pmjones** [comment]
Huh! It should be auto-updating. I'll ask the Packagist folks about it. Thanks for letting me know.

**Comment by pmjones** [comment]
FWIW, I just hit "force update" and it showed up. I'll still contact the Packagist folks, though.
