### ISSUE TITLE
insert->addRows() with only one array element generates incorrect result.

### ISSUE THREAD

**Issue by arcturial** [auraphp/Aura.SqlQuery#60]
When you do the following:

``` php
$data = array(
    array('col1' => 'val1', 'col2' => 'val2')
);

$insert = $builder
    ->newInsert()
    ->into('tablename')
    ->addRows($data);

```

The query is generated without any values. It seems the cause is line 269 in `Common/Insert`

``` php
public function addRow(array $cols = array())
{
    if (! $this->col_values) {
        return $this->cols($cols);
    }
    ...
```

It seems that because we only have one row, that function returns instead of calling `finishRow()`. This causes the data to not correctly "flush" to the appropriate variables. Any particular reason why this function is returning at that point?

**Comment by pmjones** [comment]
Do me a favor: move this code from addRow() ...

```
    if (! $this->col_order) {
        $this->col_order = array_keys($this->col_values);
    }
```

... into finishRow(), like so:

```
    if (! $this->col_values) {
        return;
    }

    // RIGHT HERE:
    if (! $this->col_order) {
        $this->col_order = array_keys($this->col_values);
    }

    foreach ($this->col_order as $col) {
        $this->finishCol($col);
    }

    $this->col_values = array();
    $this->bind_values = array();
```

Let me know if that solves it for you.

**Comment by pmjones** [comment]
No, it does not. Continuing to debug.

**Comment by arcturial** [comment]
Removing the return solved it for me, but haven't done any in depth testing to see if it causes other things to break.

**Comment by pmjones** [comment]
Found the problem, writing tests now.

**Comment by pmjones** [comment]
There, try the new develop-2 and see how it works for you.

**Comment by pmjones** [comment]
@arcturial ping -- did this fix do the trick for you?

**Comment by arcturial** [comment]
Tested it now, looks good.

However, why is it that when I install `aura/sqlquery: "*"` or `aura/sqlquery: "dev-develop-2"` I don't get the latest revision but rather reference 47524f9? that reference seems to be the parent commit of this one.

**Comment by pmjones** [comment]
47524f9 is the 2.4.0 tag. I don't know why Packagist would be doing that. I just did a force-update there, perhaps that will help.
