### ISSUE TITLE
Subquery should check for interface not extending abstractquery

### ISSUE THREAD

**Issue by auroraeosrose** [auraphp/Aura.SqlQuery#62]
The fix for using a subselect as a where item breaks when used with sqlmapper_bundle and anything else that might use composition instead of direct inheritance for a query builder class

 https://github.com/auraphp/Aura.SqlQuery/commit/bc4a1fb2a2d25a78d0b64432dddab5ac1f7d583c#diff-99f68aad8e6850c09d918a732ff868e3R333

It fails with cannot bind value of type object to placeholder - in fact a nice feature might be to check for stringability in ANY object bound into a where

In any case the current code is checking for direct inheritance of abstractquery, should probably use a different kind of check - or change sqlmapper_bundle to use more direct inheritance for it's query builder classes so things don't break

**Comment by pmjones** [comment]
To make it more obvious, can you paste a snippet of offending code? I believe you, I just want to see it to get a better handle on it.

**Comment by auroraeosrose** [comment]
This is kind of psuedocode, but you get the idea

$sub_select = $this->mapper_locator->something->select();
$sub_select->distinct();
$sub_select->cols(['t.id']);
$sub_select->innerJoin('table t','t.id = something.id');
$sub_select->where('something.value = ?', $value);

$select = $this->mapper_locator->item->select();

// this works
$select->where('item_id IN(' . $sub_select->__toString() . ')');
$select->bindValues($sub_select->getBindValues());

// this fails
$select->where('item_id IN(?)', $sub_select); <- should probably check for an interface instead of extending an abstract class because of compositional inheritence :(

$select->orderBy([$orderby]);
$select->setPaging($paging);
$select->page($page);

**Comment by pmjones** [comment]
Thanks for that, I see exactly what you mean now. Let me see what I can do.

**Comment by pmjones** [comment]
@auroraeosrose review please: https://github.com/auraphp/Aura.SqlQuery/commit/c3324aac2f5efc3e9e9e4bb56ac1c5178e243502

(This is in the temporary "stmtiface" branch.)

Would then need to have the SqlMapper Select class implement getStatement(), but that should be straightforward.

**Comment by auroraeosrose** [comment]
getStatement interface probably needs a way to getValues as well if there are values bound to the statement - right?

**Comment by pmjones** [comment]
In this particular case there are no bound values getting brought in -- at least not that I recall.

**Comment by auroraeosrose** [comment]
.... I have a ? bound in the subselect that will need to go into the main select... unless the getStatement is emulating prepares :(

**Comment by pmjones** [comment]
I thought that functionality was already in place ... and it is! I have added a test as proof, cf. the new PR #70. Let me know if that looks like it covers your case.

**Comment by pmjones** [comment]
Oh wait no it does not. :-/ It honors the different placeholders but does not bring the values forward. Working on it now.

**Comment by pmjones** [comment]
There, _now_ #70 imports the bound values from the subselect. @auroraeosrose please review.

**Comment by pmjones** [comment]
@auroraeosrose ping

**Comment by auroraeosrose** [comment]
looks good to me - now to make sure that mapper bundle uses it too :)

**Comment by pmjones** [comment]
Yeah, that'll be a followup. If you want to send a PR for it that will speed things up.
