### ISSUE TITLE
Fatal error: Method Aura\SqlQuery\Mysql\Select::__toString() must not throw an exception

### ISSUE THREAD

**Issue by elazar** [auraphp/Aura.SqlQuery#64]
I think the behavior added in #13 (specifically by commit 7053f10bcf1c8dd009320686693cdd83ad1fb060) to cause an exception to be thrown when no columns are specified isn't having quite the intended effect.

```
05:39:34 $ php -v
PHP 5.5.23 (cli) (built: Mar 22 2015 18:55:51)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
05:40:11 $ php test.php
PHP Fatal error:  Method Aura\SqlQuery\Mysql\Select::__toString() must not throw an exception in /Users/matt/blopdev/blopboard-api/test.php on line 0
PHP Stack trace:
PHP   1. {main}() /Users/matt/blopdev/blopboard-api/test.php:0
```

Here's `test.php` from the above example:

``` php
<?php
require __DIR__ . '/vendor/autoload.php';
$factory = new \Aura\SqlQuery\QueryFactory('mysql');
$select = $factory->newSelect();
$select
    ->from('table');
var_dump((string) $select);
```

Per [the PHP manual](http://php.net/manual/en/language.oop5.magic.php#object.tostring), an exception should not be thrown from `__toString()`, else it results in a (rather unintuitive) fatal error.

Here's the relevant trace:
- [`AbstractQuery->__toString()`](https://github.com/auraphp/Aura.SqlQuery/blob/7916782b1e120dd11c8614207198cf4a01b673f2/src/AbstractQuery.php#L134)
- [`AbstractQuery->getStatement()`](https://github.com/auraphp/Aura.SqlQuery/blob/7916782b1e120dd11c8614207198cf4a01b673f2/src/AbstractQuery.php#L146)
- [`Common\Select->build()`](https://github.com/auraphp/Aura.SqlQuery/blob/7916782b1e120dd11c8614207198cf4a01b673f2/src/AbstractQuery.php#L146)
- [`Common\Select->buildCols()`](https://github.com/auraphp/Aura.SqlQuery/blob/7916782b1e120dd11c8614207198cf4a01b673f2/src/Common/Select.php#L734)

I'm unsure how this should be fixed, but ideally the result would be a more intuitive error message, or at the very least documentation of this behavior in the README.

**Comment by koriym** [comment]
How about wrap whole procedure in `__toString()` with  `try-catch` , then error_log($e) and return error string ? The error string may '' or error message. 

I'm not sure what is the best practise, this is the way in my project. We can't "catch" an exception, but can see the original error in log at least.

**Comment by harikt** [comment]
Hm, the problem occurred due to no columns specified. May be try catch for select may work, but it gives no error reported which is another drawback. May be specifically mention in docs you should keep the columns.

**Comment by elazar** [comment]
Or make columns default to `'*'` in `buildCols()` if empty? Not sure that's ideal either, but it would make the error condition moot.

**Comment by harikt** [comment]
@elazar :) that was discussed earlier, but not preferred.

**Comment by elazar** [comment]
@koriym The only issue I have with emitting an error instead of throwing an exception is that PHP won't natively emit a backtrace unless something like Xdebug is present. Not sure such a backtrace would look particularly nice when logged and/or wouldn't be truncated, but otherwise the end user has no indication of where the faulty query is.

**Comment by pmjones** [comment]
This one's been a bit of a back-and-forth. Someone else had a similar problem with __toString(), so we added getStatement() to avoid the fatal errors. Cf #30 . Would the getStatement() method salve your woes here?

**Comment by pmjones** [comment]
Of course all the docs say __toString(); I failed to update them with getStatement(), so there's no way you'd know it exists. Will remedy that now.

**Comment by elazar** [comment]
@pmjones Ah! Indeed, `getStatement()` should serve my purposes. For some reason, despite my tracing through and encountering that, the thought didn't occur to me to just invoke it directly until now. :) And yes, I suspect updating the docs will definitely make that more obvious. Thanks!

**Comment by pmjones** [comment]
Thank the goodness. I have just pushed doc changes as well. Thanks for your patience.
