### ISSUE TITLE
Binding multiple values from where() doesn't work?

### ISSUE THREAD

**Issue by elazar** [auraphp/Aura.SqlQuery#66]
This is [a segment](https://github.com/auraphp/Aura.SqlQuery/blame/7916782b1e120dd11c8614207198cf4a01b673f2/README.md#L176) from the `SELECT` section of the README file:

```
N.b.: The *where(), *having(), and *join*() methods all take an optional final parameter, a sequential array of values to bind to sequential question-mark placeholders in the condition clause.
```

If I'm reading this right, this feature doesn't actually work correctly. Here's a test case:

``` php
require __DIR__ . '/vendor/autoload.php';
$factory = new \Aura\SqlQuery\QueryFactory('mysql');
$select = $factory->newSelect();
$select
    ->cols(['*'])
    ->from('table_name')
    ->where('id IN (?, ?)', [1, 2]);
var_dump((string) $select, $select->getBindValues());
```

Here's the output I get running this under PHP 5.5.23 and aura/sqlquery 2.4.2:

```
string(63) "SELECT
    *
FROM
    `table_name`
WHERE
    id IN (:_1_, :_2_)"

array(2) {
  ["_1_"]=>
  array(2) {
    [0]=>
    int(1)
    [1]=>
    int(2)
  }
  ["_2_"]=>
  NULL
}
```

The query is fine, but the bound values should look like this:

```
array(2) {
  ["_1_"]=> int(1)
  ["_2_"]=> int(2)
}
```

I can't speak to whether this applies to `having()` or `join()` because I haven't tested them. I originally found this while attempting to use this feature in a `DELETE` statement since `Common\Select` and `Common\Delete` both appear to call out to `AbstractQuery->addWhere()` to handle this.

**Comment by pmjones** [comment]
IIRC what ought to work is this:

```
->where('id IN (?, ?)', 1, 2);
```

Note that the 1 and 2 are separate params, not array elements.

If you are using Aura.Sql and its ExtendedPdo, this becomes a bit easier:

```
->where('id IN (?)', [1, 2]);
```

ExtendedPdo automatically creates a quoted comma-separated value string from an array, so the `?` gets replaced with `'1', '2'`.

Does that help at all?

**Comment by pmjones** [comment]
Reading the code and the README, the README appears wrong. It should not be "a sequential array of values" but more like "each param maps to a ?-mark placeholder." I'll make that change.

**Comment by pmjones** [comment]
Here is how the corrected README will appear:

> N.b.: The `*where()` and `*having()` methods take an arbitrary number of trailing arguments, each of which is a value to bind to a sequential question-mark placeholder in the condition clause.
> 
> Similarly, the `*join*()` methods take an optional final argument, a sequential array of values to bind to sequential question-mark placeholders in the condition clause.

I did not previously recognize the inconsistency between where()/having() and join(); changing them now would incur a BC break. I'll keep note of this for a future major-version release.

Let me know if the modified README language solves your problem.

**Comment by elazar** [comment]
Yup, this change clarifies the issue for me. Thanks.
