### ISSUE TITLE
Remove restriction requiring FROM specification before JOIN

### ISSUE THREAD

**Issue by elazar** [auraphp/Aura.SqlQuery#69]
Presently, when building a `SELECT` statement, `from()` [must be called](https://github.com/auraphp/Aura.SqlQuery/blob/2dff47fd765814705813364f3af6c92c679d2214/src/Common/Select.php#L401-403) before `join()`. My understanding is that this is more for semantic (i.e. `JOIN` essentially being a sub-clause of `FROM`) than logical / logistical reasons. There are [use cases](https://twitter.com/elazar/status/603957835957837824) that would be supported by not having this restriction.

While I may attempt implementing this myself at some point, I'm uncertain of how soon that will be. As such, I'm filing this issue in case anyone else runs into the same situation and/or wants to try to implement it themselves.

**Comment by pmjones** [comment]
Well, it's been a year. @elazar do you feel this is still something that's needed? Or is it a doc fix, where we say "you must call from() before join()" ?

**Comment by elazar** [comment]
I'd call it a "nice to have." If a code change isn't made, a doc change probably should be.

**Comment by pmjones** [comment]
@elazar Please review PR #96 , which is an attempt at fixing this issue.

**Comment by pmjones** [comment]
Fixed by #96; please open a new issue if it doesn't work the way it should. Thanks!
