### ISSUE TITLE
Can't JOIN two queries in a UNION to the same unaliased table

### ISSUE THREAD

**Issue by elazar** [auraphp/Aura.SqlQuery#73]
Using aura/sqlquery 2.4.2.

Test case:

``` php
echo (string) $select
    ->cols([
        '...'
    ])
    ->from('a')
    ->join('INNER', 'c', 'a_cid = c_id')
    ->union()
    ->cols([
        '...'
    ])
    ->from('b')
    ->join('INNER', 'c', 'b_cid = c_id');
```

Expected output:

``` sql
SELECT ...
FROM a
INNER JOIN c ON (a_cid = c_id)
UNION
SELECT ...
FROM b
INNER JOIN c ON (b_cid = c_id)
```

Actual output:

```
Cannot reference 'INNER JOIN c' after 'INNER JOIN c' in vendor/aura/sqlquery/src/Common/Select.php(406): Aura\SqlQuery\Common\Select->addTableRef('INNER JOIN', 'c')
```

Because the expected SQL above is legal, it seems like this is a bug that should be fixed.

That said, there are two potential work-arounds:
1. Alias `c` with a different alias in both `SELECT` statements.
2. Alias the `JOIN` column from each of `a` and `b` to a common name, wrap the entire query in an additional `SELECT`, and move the offending `JOIN` to be part of the new outer query with the `JOIN` column using the added column alias.

**Comment by pmjones** [comment]
Yes, sounds like a bug -- probably not clearing the internal "table references" property.

**Comment by pmjones** [comment]
I think this is remedied by the referenced PRs. Please let me know if it is not.

**Comment by elazar** [comment]
Thanks @pmjones and @dstockto! :trophy:
