### ISSUE TITLE
getStatement not reconized in IDE

### ISSUE THREAD

**Issue by gsouf** [auraphp/Aura.SqlQuery#76]
When we build a select query : 

``` php
    $factory= new QueryFactory("mysql");
    $query = $factory->newSelect(); 
    $query->getStatement();
```

the method `getStatement()` is not reconized in the ide and that leads to confusion and maybe is it highlighting a mistake in the library design ?

**Comment by harikt** [comment]
Hi, 

I missed to know what IDE are you using and what do you expect / wrong in it ?

Thank you

**Comment by staabm** [comment]
I guess the reason is that, `newSelect()` has a phpdoc which tells us it returns a `SelectInterface` but `getStatement` is not part of that interface.

`getStatement` is only defined on the `Select` class.

**Comment by gsouf** [comment]
Hi @harikt no matter the IDE, as said @staabm `getStatement` is not part of the `selectInfterface` then any IDE can know that the method exists. That's why I'm telling it's maybe a library design error.

Contributing for me is not a problem, I just would like to know your mind on the question

**Comment by staabm** [comment]
Since all `Select` classes provided by the lib extend `Common\Select` you could use this type in the phpdoc instead of `SelectInterface`.

@harikt why does the `SelectInterface` exist in the first place?

**Comment by harikt** [comment]
Thank you @staabm , @gsouf for explaining.

This have something to do with https://github.com/auraphp/Aura.SqlQuery/issues/30 . ie why `getStatement` was not in the Interface . Hope that helps.

Thank you.

**Comment by gsouf** [comment]
Ok, because it's a BC break I understand why it's not in the interface.

But wouldnt be smarter to add it in the interface and eventually bump to the version `2.6` ? 

In my opinion it's a real issue to not having it in the interface

**Comment by harikt** [comment]
2.x.y . 

x -> feature 
y-> bug fix.

So 2.6 is feature but it should not be a BC break. I know there are some which don't care the numbers. So in 3.x you can expect I guess. You can get some information about 3.x from http://auraphp.com/blog/2015/03/27/aura-3-plans/ . I hope @pmjones can resolve this issue either bumping to 3.x. That may probably need more considerations.

**Comment by gsouf** [comment]
Sorry my mistake, I didnt take in account that adding to the interface would break other implementations and not only the internal stuff. You are right about `3.0`

In the interim i'll add it to the stubs, just let me know if every query object that implements the interface `QueryInterface` do have a `getStatement` method ?

I mean this should be part of QueryInterface and not only SelectInterface, right ?

**Comment by harikt** [comment]
I will say, you wait to hear from @pmjones .

Thank you.
