### ISSUE TITLE
How can I use the Aura.SqlQuery build an update query like this

### ISSUE THREAD

**Issue by vosey** [auraphp/Aura.SqlQuery#79]
Hi, I want to use Aura.SqlQuery build an update query just like this: "Update table SET field=field+1
.but,  use "set('field','field + 1')"  does not work properly.  

How can I do ?

**Comment by staabm** [comment]
per docs, raw-values like that should work out of the box:
https://github.com/auraphp/Aura.SqlQuery#update

**Comment by pmjones** [comment]
@staabm is right, it should work properly. What specifically happens when you try `set('field', 'field+1')` ?

**Comment by vosey** [comment]
@staabm @pmjones ,thanks, I try it again, it works properly this time, I found some errors in my code, sorry.
