### ISSUE TITLE
Wrong work with IN () syntax with PostgreSQL

### ISSUE THREAD

**Issue by seyfer** [auraphp/Aura.SqlQuery#81]
Hello

I'm trying to use SQL syntax IN () or NOT IN() but it's not work correct for PostgreSQL

```
$orderStates = [1, 2];
...
$select->where('o.state in (:listStatement)')
                   ->bindValue('listStatement', $orderStates);
```

got error

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "Array"
```

And if i'm trying to prepare string

```
$orderStates = [1, 2];
...
$listStatement = implode(",", $orderStates);
$select->where('o.state in (:listStatement)')
                   ->bindValue('listStatement', $listStatement);
```

got error

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "2,1"
```

and last error is what i'm writing about. 
Bug there is not necessary " " around values. Builder generates 

```
IN ("1,2")
```

but should be

```
IN (1, 2)
```

Please, fix it!

**Comment by sjerdo** [comment]
I'm using the following code for a variable amount of values in a `WHERE field IN (values)`

```
<?php
call_user_func_array(
    [$query, 'where'],
    array_merge(['stationID IN (?' . str_repeat(',?', count($values) - 1) . ')'], $values)
);
```

**Comment by seyfer** [comment]
@sjerdo you are not using any bind() too, it's bad for security.
Values for IN() should be filled with bindValue() correctly.

**Comment by seyfer** [comment]
@sjerdo, about code you have showed - if it's solving the problem, it should be packed in method inside Aura classes somehow, because nobody would like to repeat this mess every time in their projects.

**Comment by harikt** [comment]
Are you guys using Aura.Sql to run the queries ? or pdo ?

If you are using https://github.com/auraphp/Aura.Sql#the-perform-method it should work.

PDO cannot handle IN values automatically , see https://github.com/auraphp/Aura.Sql#array-quoting

**Comment by seyfer** [comment]
I never thought about Aura.Sql exists.

It's better to add more information and examples to Aura.SqlQuery readme about Aura.Sql ExtendedPDO.

**Comment by sjerdo** [comment]
@seyfer The values are bound by giving them as arguments to the where method.
@harikt I'm indeed using Aura.Sql to run the queries. The perform method was just what I was looking for. Thanks

**Comment by pmjones** [comment]
@sjerdo It sounds like the perform() method is what you needed, then. I'm closing this issue as a result. Please let me know if it needs to be re-opened.
