### ISSUE TITLE
Where should i config the database parameters like dbhost, dbname, dbuser, dbpass?

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.SqlQuery#82]
I didn't find it in the documentation? So, how's the proper way to set them?

**Comment by Zetaphor** [comment]
This library does not handle database connections, from the readme:

> These builders are independent of any particular database connection library

To put it another way, this library only handles generating SQL queries using an ORM like syntax. The actual connection to the database and execution of the queries is intended to be handled by something else, preferably PDO. I personally use the ExtendedPDO class from [Aura.Sql](https://github.com/auraphp/Aura.Sql)

Check out [this blog post](http://auraphp.com/blog/2013/10/21/aura-sql-v2-extended-pdo/) for more information

**Comment by harikt** [comment]
Hi @javasworks ,

@Zetaphor is correct, you can either use [Aura.Sql](https://github.com/auraphp/Aura.Sql#lazy-connection-instance) or PDO .  This is also mentioned over https://github.com/auraphp/Aura.SqlQuery#getting-started . In case if you think it can be improved feel free to open a Pull Request.

I am closing the issue hoping it is addressed. Let me know if you still have any trouble. We are also in google groups ( https://groups.google.com/d/forum/auraphp ) .

Thank you.
