### ISSUE TITLE
@return self vs @return $this in docblocks

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.SqlQuery#86]
Having an issue with phpStorm autocompletion. For this code

``` php
        $query = $queryFactory->newSelect()
            ->from($this->getTableName())
            ->where(self::ID_FIELD . '= :recordID')
            ->bindValues(['recordID' => $recordID]);
```

phpStorm is unable to autocomplete `bindValues()` and any subsequent method from $query because all the fluent functions are all declared `@return self`. Changing them to `@return $this` fixes it, and is probably closer to what you mean?

From https://www.phpdoc.org/docs/latest/guides/types.html

> self An object of the class where this type was used, if inherited it will still represent the class where it was originally defined.
> $this This exact object instance, usually used to denote a fluent interface.

and from https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md

> 13 self, the element to which this type applies is of the same class as which the documented element is originally contained.
> ...
> 15 $this, the element to which this type applies is the same exact instance as the current class in the given context. As such this type is a stricter version of static as, in addition, the returned instance must not only be of the same class but also the same instance.
> This type is often used as return value for methods implementing the Fluent Interface design pattern.

So I think `@return $this` is probably what you mean? (because the classes implement a fluent interface). Will you accept a pull request to change these over?

**Comment by harikt** [comment]
If that is the correct behavior what is the problem accepting a PR :+1:  . I was doing a quick search on https://github.com/doctrine/doctrine2/blob/276a22fb6fe6659717be12531766e0abf48e7fbb/lib/Doctrine/ORM/Mapping/Builder/AssociationBuilder.php#L61 . Seems in doctrine they use return class name. But what ever is good, we are good to go.

Thank you for investing your time looking into this.

**Comment by pmjones** [comment]
$this vs self went back-and-forth a long time ago in PHPDocumentor; iirc they used to mean the same thing. If they are different now, and $this means "this actual instance" then yeah, PR welcome. Thanks for the attention to detail.
