### ISSUE TITLE
Offset ignored when no limit is specified

### ISSUE THREAD

**Issue by Torgan** [auraphp/Aura.SqlQuery#88]
Hello, 

It looks like that the select query builder ignore the offset value if no limit is provided, which it shouldn't :

```
$queryBuilder
    ->cols('id')
    ->from('user')
    ->orderBy([ 'id' ])
    ->offset(5);
```

gives the following statement : 

`SELECT id FROM "user" ORDER BY id`

According to SQL specification, it should work just fine (it does with postgreSQL) :

`SELECT id FROM "user" ORDER BY id OFFSET 5`

With mySQL, as explained in the documentation (http://dev.mysql.com/doc/refman/5.7/en/select.html), it should be handled this way : 

```
To retrieve all rows from a certain offset up to the end of the result set, you can use some large number for the second parameter. This statement retrieves all rows from the 96th row to the last:

SELECT * FROM tbl LIMIT 95,18446744073709551615;
```

**Comment by harikt** [comment]
Thank you @Torgan for the report. Probably we need to override https://github.com/auraphp/Aura.SqlQuery/blob/ddf3d544cabcda0090e3f4975585d67d74d0968f/src/AbstractQuery.php#L474 for postrgres.

**Comment by Torgan** [comment]
Yes, looks like it's the way to go. Could be done for mySQL also I guess.
