### ISSUE TITLE
INSERT FROM SELECT?

### ISSUE THREAD

**Issue by benguild** [auraphp/Aura.SqlQuery#89]
Is it possible to do something like this...

```
INSERT INTO table ("someColumn") SELECT "ABC" AS "someColumn" FROM DUAL WHERE NOT EXISTS (some condition)
```

I guess you could build an [INSERT INTO ...] query and then the SELECT and join them as a string, but I wasn't sure if that was the wrong approach.

Also, I don't see the "DUAL" keyword included... so I assume you'd have to do like fromRaw('DUAL') ?

**Comment by harikt** [comment]
no. I don't think this is possible in the current scenario.

**Comment by benguild** [comment]
:( ok.

**Comment by harikt** [comment]
@benguild actually you could write something to make this happen. Interested to send a PR ?

**Comment by benguild** [comment]
@harikt I'd love to, but honestly I really don't have time right now and I'm moving away from PHP in the longterm. Sorry

**Comment by harikt** [comment]
Sure, no problem.

**Comment by pmjones** [comment]
@benguild If you're still interested in `INSERT INTO ... SELECT` functionality, please re-open this issue, and/or submit a PR for it. Thanks!

**Comment by designermonkey** [comment]
I know this is a very old issue, but...

```
INSERT INTO prices (group, id, price) 
SELECT 7, articleId, 1.50
from article 
WHERE name LIKE 'ABC%'
```

This is a pretty standard query to expect a query builder to support. Can the maintainers of this library not implement this without expecting users (who are generally very busy writing production code) to submit it as a PR?

**Comment by pmjones** [comment]
> Can the maintainers of this library not implement this without expecting users (who are generally very busy writing production code) to submit it as a PR?

The maintainers are generally very busy writing production code too; I for one have never encountered the scenario described in this issue. But if you want to submit a PR for it, you'll get credit for doing so.
