### ISSUE TITLE
Join and From conflict

### ISSUE THREAD

**Issue by metalfox6383** [auraphp/Aura.SqlQuery#90]
Hello:
I'm building my sentence. I can't use "join" function before "from" function. When I tried, my app give me thist error: "Cannot join() without from() first." Line 453 of \src\Common\Select.php

Your description says I can use the functions with any order. I check your file and I guess you must use other array for "join" part.

I like this lib, is very usefull. Thanks.

**Comment by pmjones** [comment]
Ah yes, we need to either (1) correct the documentation, or (2) figure out a way to subordinate JOINs added before a FROM to the first FROM added after that.

**Comment by metalfox6383** [comment]
Great! Please, take option 2. Thanks and greetings.

**Comment by pmjones** [comment]
@metalfox6383 Please review PR #96 , which is an attempt at fixing this issue.

**Comment by pmjones** [comment]
Fixed by #96; please review and open a new issue if it does not work the way you'd like. Thanks!

**Comment by metalfox6383** [comment]
Thanks. I will check.
