### ISSUE TITLE
orderby

### ISSUE THREAD

**Issue by javansolo** [auraphp/Aura.SqlQuery#93]
hello
how set order type **DESC** on **MySql**?

**Comment by harikt** [comment]
Try 

```
->orderBy(array('id DESC',[optional fields]))
```

**Comment by javansolo** [comment]
yes
Please put in the description.

**Comment by harikt** [comment]
@javansolo there is already an example of `orderBy` iirc.

If not please consider sending a PR.

@pmjones recently in a discussion I got a question why is `orderBy` accepting array than a string?

Thank you.
