### ISSUE TITLE
Issue: missing parentheses () support for WHERE conditions

### ISSUE THREAD

**Issue by yespire** [auraphp/Aura.SqlQuery#97]
examples:
where query1 AND (query2 OR query3) AND query4
where query1 OR (query2 AND query3) OR query4
where query1 OR (query2 AND (query3 XOR (query4 AND query5)))

**Comment by pmjones** [comment]
You should be able to do this by adding "partial" parentheses to your WHERE clauses. For example:

```
// where query1 AND (query2 OR query3) AND query4
$select->where('query1');
$select->where('(query2');
$select->orWhere('query3)');
$select->where('query4');
```

Alternatively, you can put the `OR` in there yourself:

```
// where query1 AND (query2 OR query3) AND query4
$select->where('query1');
$select->where('(query2 OR query3)');
$select->where('query4');
```

Let me know if that helps or not.

**Comment by taxp** [comment]
Shouldn't parentheses be added by default in Aura\SqlQuery\AbstractQuery::indent(array $list)?
I mean now it is some kind of 'linear' stack of single operands while it'd be more expectable if every set of operands inside where/orWhere considered as independent part.
