### ISSUE TITLE
Option to hide columns when * is selected

### ISSUE THREAD

**Issue by melvinchia** [auraphp/Aura.SqlQuery#98]
Is it feasible to have an option to hide columns when \* is selected?

$queryfactory->newSelect()->cols(['*']->hideCols(['col1', 'col2', 'col3', 'col4']);

This request may sound strange, but I have a table with 50 columns and I want 5 columns hidden. I can either provide a 45-column array, or select \* and specify the 5 columns I want hidden from the results. Is this a feasible feature request?

**Comment by pmjones** [comment]
> I have a table with 50 columns and I want 5 columns hidden. I can either provide a 45-column array, or select \* and specify the 5 columns I want hidden from the results

Ahh, that's a tough one. Let's work through it a bit. First question: if you were trying to implement that in plain SQL, how would you do it?

**Comment by melvinchia** [comment]
I was thinking it might be able to happen AFTER the sql query, as the object/array is being created the specified hidden columns could be dropped, then the final object/array returned without the hidden columns?

Should be much less painful that way?

**Comment by harikt** [comment]
@melvinchia the fact is Aura.SqlQuery don't read the table schema information. Probably you may want to use something easily via reading the tableschema and removing the unwanted columns yourself.

Thank you

**Comment by melvinchia** [comment]
@harikt Aura.SqlQuery doesn't need to read the table schema information. I could do a ->cols(['*']) and later run a foreach() loop in php to unset() the columns I don't want, or I could have it done within Aura.SqlQuery when it maps the query rows to objects, it just has to drop the specified column names.

I'm guessing my question now is, is it a feasible request for it to happen inside Aura.SqlQuery, or outside in a foreach() loop?

**Comment by harikt** [comment]
@melvinchia I guess the sort of hiding functionality is out of scope for the query builder. It sounds good for certain cases like Aura.Sql and SqlQuery is integrated. Eg : Atlas.Orm to hide things like password fields etc.

**Comment by melvinchia** [comment]
I am using Aura.Sql and Aura.SqlQuery in my build. I tried a few other ORM, but gave up after the complexity of having to build extensive datamaps or models for each and every database table I have to use...

**Comment by pmjones** [comment]
Hi @melvinchia,

Combining quotes from two of your responses:

> I was thinking it might be able to happen AFTER the sql query ... I could have it done within Aura.SqlQuery when it maps the query rows to objects

One problem here is that SqlQuery does not map query rows to objects. It doesn't actually issue the query; you pass the query (as built) through something else to get back a result set.

Based on this discussion, it sounds to me like you need a "data mapper" layer of some sort. Maybe I'm missing something about your question?

**Comment by melvinchia** [comment]
Ahh.. Ok.. I get it now.. It should be in a layer above SqlQuery.. =)

Thanks all.. Closing.
